server:
  port: 8080

spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: sa
    password:
    schema: classpath*:schema.sql
    data: classpath*:data.sql